### ISSUE TITLE
 surface = Surface.read_triangular('lh.white') has problem

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-stats#23]
`
from freesurfer_surface import Surface
surface = Surface.read_triangular('lh.white')
with open('lhedges.txt', "w") as f:
    for triangle in surface.triangles:
        for edge_vertex_indices in triangle.adjacent_vertex_indices():
            edge_vertices = surface.select_vertices(edge_vertex_indices)
            f.write("{} {}\n".format(edge_vertex_indices[0],edge_vertex_indices[1]))
`

Traceback (most recent call last):
  File "D:/my_subject/2020.7.1-7.7/2016GCN/graph-to-spectral-coordinate/fsaverage5/test1.py", line 19, in <module>
    surface = Surface.read_triangular('lh.white')
  File "D:\anaconda3.4\lib\site-packages\freesurfer_surface\__init__.py", line 431, in read_triangular
    surface._read_triangular(surface_file)
  File "D:\anaconda3.4\lib\site-packages\freesurfer_surface\__init__.py", line 424, in _read_triangular
    self.command_lines = list(self._read_cmdlines(stream))
  File "D:\anaconda3.4\lib\site-packages\freesurfer_surface\__init__.py", line 381, in _read_cmdlines
    assert tag == cls._TAG_CMDLINE  # might be TAG_GROUP_AVG_SURFACE_AREA
AssertionError

Is there a problem with the library file?

**Comment by fphammerle** [comment]
Hi,

thanks for reporting!

Could you maybe share `lh.white` ?

**Comment by tanjia123456** [comment]
Hello, the lh.white was uploaded in:    https://github.com/tanjia123456/Mindboggle_datasets

**Comment by tanjia123456** [comment]
hello, this bug can you solve? I am very confused about it.

**Comment by fphammerle** [comment]
sorry, I haven't found time to look into the bug yet.
I'll get back to you.
thanks for the upload!
